# Generated by Django 5.0.6 on 2024-08-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_basecategory'),
        ('product', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category', to='home.basecategory'),
        ),
    ]
