# Generated by Django 5.0.6 on 2024-08-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_comment_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='previous_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت قبلی'),
        ),
    ]
