# Generated by Django 5.0.6 on 2024-08-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=0, verbose_name='زمان انتشار'),
            preserve_default=False,
        ),
    ]
