# Generated by Django 5.0.6 on 2024-08-07 22:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
    ]
