# Generated by Django 5.0.6 on 2024-08-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_comment_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
    ]
