# Generated by Django 5.0.6 on 2024-08-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'عکس', 'verbose_name_plural': 'عکس ها'},
        ),
    ]
