# Generated by Django 5.0.6 on 2024-08-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_staticblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='staticblog',
            options={'verbose_name': 'مقاله پایه', 'verbose_name_plural': 'مقاله های پایه'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=250, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='category', to='article.category', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='staticblog',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='staticblog',
            name='author',
            field=models.CharField(max_length=250, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='staticblog',
            name='body',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='staticblog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='staticblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='staticblog',
            name='title',
            field=models.CharField(max_length=250, verbose_name='اسم'),
        ),
    ]
