# Generated by Django 5.0.6 on 2024-08-07 22:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_blog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='staticblog',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
    ]
