# Generated by Django 5.0.6 on 2024-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_basecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecategory',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
