# Generated by Django 5.0.6 on 2024-08-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='آدرس ایمیل'),
        ),
    ]
