# Generated by Django 5.0.6 on 2024-08-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_news_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'ایمیل خبرنامه', 'verbose_name_plural': 'ایمیل های خبرنامه'},
        ),
    ]
