# Generated by Django 5.0.6 on 2024-08-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=1, max_length=11, verbose_name='کد پستی'),
            preserve_default=False,
        ),
    ]
